-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. PROFILES (Extends Supabase Auth)
create table public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  username text unique,
  full_name text,
  avatar_url text,
  balance numeric default 10000, -- Virtual wallet balance in USD (starts with $10,000)
  updated_at timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS for Profiles
alter table public.profiles enable row level security;
create policy "Public profiles are viewable by everyone." on public.profiles for select using (true);
create policy "Users can insert their own profile." on public.profiles for insert with check (auth.uid() = id);
create policy "Users can update own profile." on public.profiles for update using (auth.uid() = id);

-- Trigger to create profile on signup
create function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name, avatar_url)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();


-- 2. CRYPTO ASSETS (Reference table)
create table public.crypto_assets (
  symbol text primary key, -- BTC, ETH
  name text not null,
  coin_cap_id text unique not null, -- bitcoin, ethereum
  rank integer,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.crypto_assets enable row level security;
create policy "Assets are viewable by everyone." on public.crypto_assets for select using (true);


-- 3. MARKET DATA (TimeSeries)
create table public.market_data (
  id bigint generated by default as identity primary key,
  crypto_symbol text references public.crypto_assets(symbol) on delete cascade not null,
  price_usd numeric not null,
  market_cap_usd numeric,
  volume_24h_usd numeric,
  change_percent_24h numeric,
  timestamp timestamp with time zone default timezone('utc'::text, now()) not null
);
create index idx_market_data_symbol_time on public.market_data(crypto_symbol, timestamp desc);
alter table public.market_data enable row level security;
create policy "Market data is viewable by everyone." on public.market_data for select using (true);


-- 4. PORTFOLIO TRANSACTIONS
create table public.transactions (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  crypto_symbol text references public.crypto_assets(symbol) not null,
  type text check (type in ('BUY', 'SELL', 'DEPOSIT', 'WITHDRAW')) not null,
  amount numeric not null, -- Quantity of coins (or USD for DEPOSIT/WITHDRAW)
  price_per_coin numeric, -- Price at time of transaction (null for DEPOSIT/WITHDRAW)
  total_cost numeric not null, -- Total USD value of the transaction
  timestamp timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.transactions enable row level security;
create policy "Users can view own transactions." on public.transactions for select using (auth.uid() = user_id);
create policy "Users can insert own transactions." on public.transactions for insert with check (auth.uid() = user_id);


-- 5. ALERTS
create table public.alerts (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  crypto_symbol text references public.crypto_assets(symbol) not null,
  target_price numeric not null,
  condition text check (condition in ('ABOVE', 'BELOW')) not null,
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.alerts enable row level security;
create policy "Users can view own alerts." on public.alerts for select using (auth.uid() = user_id);
create policy "Users can manage own alerts." on public.alerts for all using (auth.uid() = user_id);
